// <auto-generated />
using Agreement.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Agreement.Migrations
{
    [DbContext(typeof(AgreementDbContext))]
    partial class AgreementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Agreement.Models.AgreementModel", b =>
                {
                    b.Property<string>("CNPCUI")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<bool>("AcordPrelucrareDate")
                        .HasColumnType("bit");

                    b.Property<bool>("ComunicareEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("ComunicareMarketing")
                        .HasColumnType("bit");

                    b.Property<bool>("ComunicarePosta")
                        .HasColumnType("bit");

                    b.Property<bool>("ComunicareSMS")
                        .HasColumnType("bit");

                    b.Property<string>("DenumireCompanie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Judet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NrTelefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CNPCUI");

                    b.ToTable("Agreements");
                });
#pragma warning restore 612, 618
        }
    }
}
